### ISSUE TITLE
how do i log everything to stdout, including web requests?

### ISSUE THREAD

**Issue by dfuentes77** [jsimone/webapp-runner#110]

**Comment by jkutner** [comment]
@dfuentes77 Are you trying to get the behavior or [`AccessLogValve`](https://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Access_Log_Valve) but with STDOUT instead of a file?

**Comment by dfuentes77** [comment]
yes, including that.  I also want to log all INFO level logs from the application.   I'm not sure if that's default under webapp-runner?

**Comment by jkutner** [comment]
@dfuentes77 I think your application logs will need to be configured independently. What logging framework are you using?

**Comment by dfuentes77** [comment]
@jkutner Works great!

**Comment by jkutner** [comment]
This will be available in 8.5.32.1 and 9.0.8.1 on Maven Central in the next hour or two. I'm going to close the issue, but we can reopen it if you have problems.

**Comment by dfuentes77** [comment]
Awesome, very cool.  Thanks Joe!
