### ISSUE TITLE
double Content-Length headers when proxied behind nginx

### ISSUE THREAD

**Issue by dfuentes77** [jsimone/webapp-runner#115]
We're seeing this:
```
$ curl --verbose -I -X GET https://<our hostname/path>/api/1.0/authenticate 2>&1|grep 'Content-Length'
< Content-Length: 0
< Content-Length: 0
Content-Length: 0
Content-Length: 0
```
which causes weird behavior in certain browsers and with using node's express. 

This is how we are launching it:
```
/usr/bin/java $JAVA_OPTS -jar $SERVER/build/webapp-runner.jar --temp-directory /tmp --access-log --access-log-pattern combined --path /<our path> $SERVER/build/libs/<our war>
```

And this is how we are proxy'ing it in nginx:
```
location /<our path>/ {
    proxy_pass http://localhost:8080/<our path>/;
    proxy_set_header Host $host;
    proxy_set_header X-Request-Start "t=${msec}";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

We just noticed this since our prior version of Tomcat wasn't doing this.  It was not webapp-runner.

We would really appreciate any assistance.  Thanks!

**Comment by dfuentes77** [comment]
So on further investigation, I'm realizing our previous Tomcat was NOT sending a `Content-Length` header.  Our AWS ELB is returning the Content-Length itself.  Now, this Tomcat is sending a `Content-Length` as well, so along with the ELB, 2 `Content-Length` headers are getting returned to the request.

**Comment by jkutner** [comment]
I'm not sure if there's a way to disable that header.

At what version did this change?

**Comment by dfuentes77** [comment]
Sorry, it looks like the previous version of Tomcat wasn't sending the `Content-Length: 0` header as required by RFC for 205 responses, but this new one does, as it should.  So far we're finding the Amazon's ELB is sending a dupe `Content-Length` header and we're still trying to find out why.   I'll close this for now unless I find something contradictory.  Thanks @jkutner
