### ISSUE TITLE
Redis JCache provider conflict with application JCache provider

### ISSUE THREAD

**Issue by JavaWebinar** [jsimone/webapp-runner#124]
Tomcat 9 webapp-runner include Redis JCache provider 
`META-INF/services/javax.cache.spi.CachingProvider`
My application used Ehcache 3.x (JCache implementation) with own `ehcache-3.6.1.jar!\META-INF\services\javax.cache.spi.CachingProvider`, but try to instatiate Redis client and fall down.
Propose to eliminate `META-INF/services/javax.cache.spi.CachingProvider` from Tomcat 9 webapp-runner.jar

**Comment by jkutner** [comment]
Have you tried using:

```
<dependency>
  <groupId>com.github.jsimone</groupId>
  <artifactId>webapp-runner-main</artifactId>
  <version>9.0.14.0</version>
</dependency>
```

This is described in https://github.com/jsimone/webapp-runner#using-without-memcached-or-redis

Will that fix the problem for you?

**Comment by JavaWebinar** [comment]
Thank you, problem fixed.
Sorry for careless doc reading.
