### ISSUE TITLE
Is it possible to open both a port and an httpsPort?

### ISSUE THREAD

**Issue by josdejong** [jsimone/webapp-runner#141]
We are looking for a replacement for the `tomcat7-maven-plugin` that we're currently using. `webapp-runner` looks like a perfect solution for us! So thanks for sharing this, it looks really decent :)

I was wondering if it is possible to open both a `port` and an `httpsPort`, like we do in our current setup: 

```xml
<!-- usage: mvn tomcat7:run -->
<plugin>
  <groupId>org.apache.tomcat.maven</groupId>
  <artifactId>tomcat7-maven-plugin</artifactId>
  <version>2.2</version>
  <configuration>
    <path>/</path>
    <port>9090</port>
    <httpsPort>9091</httpsPort>
    <keystorePass>...</keystorePass>
    <systemProperties>
      <javax.net.ssl.trustStore>...</javax.net.ssl.trustStore>
    </systemProperties>
  </configuration>
</plugin>
```

I see some related options in the docs like `--enable-ssl` and `--proxy-base-url` but I'm not sure how to convert our current setup. If not, we should probably open the secured port and forward the unsecured port to that or something?

**Comment by jkutner** [comment]
webapp-runner only supports one connector, so I think it can only bind to one port for http/https. I recommend the approach you suggested: forwarding to the https port.

**Comment by josdejong** [comment]
:+1: 

We are considering phasing out HTTP support in favor of just HTTPS :)
