### ISSUE TITLE
Failed test while building

### ISSUE THREAD

**Issue by aghasemi** [jsimone/webapp-runner#150]
Hi,
Running `mvn package` yields this:

`Failed tests:   clean(webapp.runner.launch.TomcatBaseDirResolutionTest): expected [true] but found [false]`

Any idea how to solve it?

**Comment by jkutner** [comment]
What OS are you using?

**Comment by aghasemi** [comment]
Windows

**Comment by jkutner** [comment]
@aghasemi i think this should be fixed now. please let me know if it still occurs.
