### ISSUE TITLE
Change Tomcat default error pages

### ISSUE THREAD

**Issue by andback** [jsimone/webapp-runner#158]
Is there a way to replace Tomcat's default error pages? (401, 404, 500, etc).

Normally this is configured in web.xml and I can't find a way to replace it.
Any other way to do this or am I missing something?

**Comment by jkutner** [comment]
You can put a web.xml in the WAR file you run with webapp-runner

**Comment by andback** [comment]
Ah, perfect. So I was missing something. Thanks!
