### ISSUE TITLE
Add some info around basic authN in README

### ISSUE THREAD

**Issue by pulkitsinghal** [jsimone/webapp-runner#31]
For example:

Specifying `--enable-basic-auth` will automatically look for a tomcat-users.xml file in your heroku-project's root directory

        if(tomcatUsersLocation == null) {
            tomcatUsersLocation = "../../tomcat-users.xml";
        }

and use it.

Explicitly specifying `--tomcat-users-location` path will automatically enable `--enable-basic-auth` flag.

Procfile
    `web:    ./webapp-runner.sh`

webapp-runner.sh
   ` java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT --enable-basic-auth target/*.war`

**Comment by jkutner** [comment]
Basic description of command line opts is in the README. Please submit a PR if you feel more docs are needed.
