### ISSUE TITLE
Memcached classloader problem

### ISSUE THREAD

**Issue by leleuj** [jsimone/webapp-runner#32]
Hi,

First of all, thanks for this great library I use for heroku !

I want to share web sessions accross multiple instances using Memcached and at the same time, my webapp is built with Spring and use Memcached (MemcachedClientFactoryBean) for internal purposes.

At startup, I have a ClassNotFoundException on the Spring FactoryBean. It seems that the classloader used is the one of the Tomcat (with Memcached dependency but not the Spring dependency) instead of the classloader of the webapp (with Spring and Memcached dependencies).

So my question is :
Is there a way to force the use of the classloader of the webapp before the Tomcat classloader ?

Thanks.
Best regards,
Jérôme

**Comment by jkutner** [comment]
In [the latest version of Webapp Runner](http://repo1.maven.org/maven2/com/github/jsimone/) you can use the webapp-runner-main library if you do not want memcached and redis libraries.
