### ISSUE TITLE
WebSockets issues

### ISSUE THREAD

**Issue by beppeben** [jsimone/webapp-runner#38]
Hi,
my webapp uses WebSockets by annotating the server code like this
@ServerEndpoint(value = "/websocket/myservlet")
It works perfecly when deployed on a real Tomcat server, but websockets don't work when run through the webapp-runner. Is it a known issue or am I doing something wrong?

**Comment by Kanaris** [comment]
Looks like, the issue still exists.

**Comment by phowells** [comment]
Easy fix for this.

Update your maven-dependency-plugin to include the tomcat-embed-websocket dependency.

`<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-dependency-plugin</artifactId>
	<version>2.3</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>copy</goal>
			</goals>
			<configuration>
				<artifactItems>
					<artifactItem>
						<groupId>com.github.jsimone</groupId>
						<artifactId>webapp-runner</artifactId>
						<version>${webapp-runner-version}</version>
						<destFileName>webapp-runner.jar</destFileName>
					</artifactItem>
					<artifactItem>
					    <groupId>org.apache.tomcat.embed</groupId>
					    <artifactId>tomcat-embed-websocket</artifactId>
					    <version>${tomcat.version}</version>
						<destFileName>tomcat-embed-websocket.jar</destFileName>
					</artifactItem>
				</artifactItems>
			</configuration>
		</execution>
	</executions>
</plugin>`

Then run webapp_runner by specifying the main class and the 2 dependencies on the classpath rather than as an executable jar.

`java $JAVA_OPTS -cp tomcat-embed-websocket.jar:webapp-runner.jar webapp.runner.launch.Main --port 8080 myWarFile.war`

**Comment by jkutner** [comment]
@phowells do you think this is something webapp-runner should bundle in it's fat jar? The only reasons not to would be if the dependency is too volatile, or too uncommonly used.

**Comment by phowells** [comment]
@jkutner Yes, ideally webapp-runner would include the websockets jar.  That way the app would not have to worry about keeping the versions in sync.  The websockets dependency is no more volatile then the other libs in the tomcat release.  If a project has a legitimate concern or restriction on the size of the webapp-runner jar then I think it would fall to that project to create a custom build to exclude the functions they do not need.  As it is, websockets are a standard part of tomcat now so it should be included in the tomcat webapp-runner.

**Comment by jkutner** [comment]
Fixed by fe2366190ac26bcb84638340341a937caf2fb4a1. Will be available in 8.11.5.3
