### ISSUE TITLE
I would like to have separate parameter for tomcat.enableNaming.

### ISSUE THREAD

**Issue by valery-barysok** [jsimone/webapp-runner#48]
As workaround i have to use --enable-basic-auth parameter with redundant tomcat-users.xml file.

**Comment by jkutner** [comment]
Yea, that's an option we can add. But probably only on the tomcat8 line (which is not master). What version on webapp-runner are you using or planning to use?

**Comment by valery-barysok** [comment]
i am using tomcat7

**Comment by jkutner** [comment]
I'll see what I can do. I wasn't planning on cutting another 7.x release. Is it possible to upgrade to Tomcat 8 (using [8.0.24.0](http://repo1.maven.org/maven2/com/github/jsimone/webapp-runner/8.0.23.0/))?

**Comment by valery-barysok** [comment]
yeah... i can... but i am using tomcat7 because it is near to target requirement that is tomcat 6.

**Comment by jkutner** [comment]
This is available in the latest version. I won't backport it though, sorry.
