### ISSUE TITLE
How would I increase the value of maxThreads with webapp-runner?

### ISSUE THREAD

**Issue by ctkdev** [jsimone/webapp-runner#52]
I am attempting to increase the maxThreads from the default number, 200, to around 350 - 400 to tweak the performance of an application that typically handles long-running http threads on Heroku.

**Comment by ctkdev** [comment]
I would like to do some performance tweaking of other items that are available in the server.xml as well.
What is the recommended way to do this with webapp-runner?

**Comment by jkutner** [comment]
I'm not sure if it's possible right now. Normally you'd set this in `server.xml`, but with embedded Tomcat I think you need to do something with the [Connector object](https://github.com/jsimone/webapp-runner/blob/master/src/main/java/webapp/runner/launch/Main.java#L89).

I'd gladly accept a PR for this.

**Comment by jkutner** [comment]
Fixed by b845bdc257b4e4e2c90a3bc6880969853f3196c6
