### ISSUE TITLE
How to dynamically reload project ?

### ISSUE THREAD

**Issue by boly38** [jsimone/webapp-runner#53]
Hi 
sorry but out of error from me, I was unable to find this option.

- is it possible to tell to webapp-runner to reload the current war (or exploded content) ?

If no:
- is it possible to add console command like 'r' key to reload the current war (or exploded content) ?

this to avoid startup time
if reloading all project make no sense, maybe an option to reload only static resources could be a good point (while developping static frontend for example)

what do you think ?

**Comment by jkutner** [comment]
You can use `--expand-war` as described here:
https://github.com/jsimone/webapp-runner#options

Reloading isn't possible, but a PR might be welcome if it's not too invasive.

**Comment by boly38** [comment]
Oo while using exploded war as input ; a update of a static resource is already dynamically available (of course need to clean the cache ..), sorry for the noise. and thanks for you feedback.
