### ISSUE TITLE
Slow startup for tomcat 8

### ISSUE THREAD

**Issue by asouza** [jsimone/webapp-runner#54]
Hi, 

I am not really sure if this is a issue... Anyway, every time I try to start, Tomcat takes several minutes... The log message that it takes more time is "org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found"

Any tips? Should I create any configuration? I tried to search, but I did not find anything.

**Comment by jkutner** [comment]
Try using `--expand-war` option. 
https://github.com/jsimone/webapp-runner#options

Start-up tends to be unacceptable without this option. It should probably be the default.

**Comment by asouza** [comment]
It worked like a charm. I am gonna take a look in the source code, to understand why this option is so important.
