### ISSUE TITLE
Is webapp-runner compatible with spring boot application  

### ISSUE THREAD

**Issue by Sergei-Rudenkov** [jsimone/webapp-runner#59]
I have an issue with webapp-runner, I cannot run Spring boot application using it. 
Could you, please, help me?
http://stackoverflow.com/questions/35221735/is-there-any-possibility-to-see-logs-of-war-file-execution

**Comment by jkutner** [comment]
With Spring-Boot you should use the embedded Tomcat that it provides.
https://spring.io/guides/gs/spring-boot/
