### ISSUE TITLE
Support for custom Valves

### ISSUE THREAD

**Issue by htutman** [jsimone/webapp-runner#67]
Hi,
I created a custom Tomcat Valve and configured it in context.xml. I tried putting the Velve implementation class in classpath when launching, but I'm getting java.lang.ClassNotFoundException:

java -cp <custom velve containing jar>.jar -jar webapp-runner.jar --context-xml context.xml --port 8888 theWar.war

When the Valve implementation is added into the webapp-runner.jar, everything is working as expected.

Is there a way to specify jar(s) where custom Valves are implemented so they can be used by Tomcat?

Thank you.

**Comment by jkutner** [comment]
Can you try:

```
java -cp webapp-runner.jar:yourapp.jar webapp.runner.launch.Main --context-xml context.xml --port 8888 theWar.war
```

**Comment by htutman** [comment]
Yes, this works! Thank you.
