### ISSUE TITLE
Tomcat versions are out of PCI Compliance

### ISSUE THREAD

**Issue by adam-sch** [jsimone/webapp-runner#69]
Tomcat 8.0.33.0 and 8.5.5.0 both fail PCI compliance. 8.0.39.0 and 8.5.8 resolve the issues.

**Comment by jkutner** [comment]
Fixed by:

* https://github.com/jsimone/webapp-runner/commit/1e5c4ea874f986070b857b434741652ab65e529f
* https://github.com/jsimone/webapp-runner/commit/753ff592f2b8f9ca42b4a10a2dd14ec1c17e80cf
