### ISSUE TITLE
Option --enable-ssl and javax.net.ssl.trustStore

### ISSUE THREAD

**Issue by Intelligent2013** [jsimone/webapp-runner#71]
I have SSL certificate issued by Certificate Authorities and would like to use https connection to my site.
I've tried to add option --enable-ssl into command line. Also, I've added java options
-Djavax.net.ssl.trustStore=fullchain_and_key.p12  and
-Djavax.net.ssl.trustStorePassword=changeit
But, when I run command file I get an error:
_SEVERE: Failed to load keystore type JKS with path /root/.keystore due to /root/.keystore (No such file or directory)_
I have not the .keystore file in home folder.
After that I've changed the parameter's name to -Djavax.net.ssl.keyStore -Djavax.net.ssl.keyStorePassword (i.e. keyStore instead trustStore) and everything is working now.
As I undestood, keyStore uses when client connects to server and checks server's certificate, but trustStore uses when server connects to other servers/client with SSL.
Or may be I did something wrong and everything should working with trustStore?

**Comment by jkutner** [comment]
The keystore in `javax.net.ssl.keyStore` is meant to contain your private keys and certificates, whereas the `javax.net.ssl.trustStore` is meant to contain the CA certificates you're willing to trust when a remote party presents its certificate. In some cases, they can be one and the same store, although it's often better practice to use distinct stores.

The `javax.net.ssl.keyStore` and `javax.net.ssl.trustStore` system properties are used to build `KeyManagers` and `TrustManagers` respectively. According to the [Oracle documentation](http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#RelsTM_KM):

> A TrustManager determines whether the remote authentication credentials (and thus the connection) should be trusted.
>
> A KeyManager determines which authentication credentials to send to the remote host.

So I don't think there's a problem. I'll close this issue, but we can reopen if I misunderstood something.

**Comment by Intelligent2013** [comment]
Thank you for the clarification.
In the README.md and in '--help' said:
>     --enable-ssl
>        Specify -Djavax.net.ssl.trustStore and -Djavax.net.ssl.trustStorePassword
>        in JAVA_OPTS. Note: should not be used if a reverse proxy is terminating SSL
>        for you (such as on Heroku)
>        Default: false

But really, the parameters -Djavax.net.ssl.keyStore and -Djavax.net.ssl.keystoreStorePassword are using also. May be these parameters also should be included in '--enable-ssl' parameter description?
