### ISSUE TITLE
Version conflict httpcore dependency

### ISSUE THREAD

**Issue by jonigl** [jsimone/webapp-runner#74]
Hi, 

I found into the webapp-runner-8.5.11.2.jar that org.apache.httpcomponents.httpcore version 4.3 is included, Is it right? I use aws-java-sdk which has httpcore 4.4.5 dependency and I have a version conflict. 

How can I remove the org.apache.httpcomponents.httpcore version 4.3 from webapp-runner-8.5.11.2.jar?

Thanks

**Comment by jkutner** [comment]
The Apache Http libs should be removed in 8.5.11.3.

There is also this packaging, which excludes all memcached and redis dependencies:

```xml
<dependency>
    <groupId>com.github.jsimone</groupId>
    <artifactId>webapp-runner-main</artifactId>
    <version>8.5.11.3</version>
</dependency>
```

**Comment by jonigl** [comment]
Thanks @jkutner for your quick answer.

I could see that webapp-runner 8.5.11.3 is already on [mvnrepository.com](https://mvnrepository.com/artifact/com.github.jsimone/webapp-runner/8.5.11.3) but is not documented ([README.md](https://github.com/jsimone/webapp-runner/blob/webapp-runner-parent-8.5.11.3/README.md)) yet in this github repository. Is it an stable version? can I use it for production? I'm using webapp-runner with Heroku.

Thanks in advance.

**Comment by jkutner** [comment]
Yes, It's stable and ready for production. I haven't had a chance to document it though.

**Comment by jonigl** [comment]
Thanks @jkutner !
