### ISSUE TITLE
webapps does not exist or is not a directory

### ISSUE THREAD

**Issue by forgo** [jsimone/webapp-runner#75]
I am still having the same issue as mentioned below with version 7.0.75:
[https://github.com/jsimone/webapp-runner/issues/40](https://github.com/jsimone/webapp-runner/issues/40)

The output is almost identical:
```bash
SEVERE: Exception fixing docBase for context []
java.io.IOException: Application base [{1}] for host [/nfs/agile_apps/integration/avery/apps/webapps/ansible/logs/next-catalogs/target/tomcat.10003/webapps] does not exist or is not a directory. deployOnStartUp and autoDeploy have been set to false to prevent deployment errors. Other errors may still occur.
```

I thought by adding --expanded-dirname in my parameters, according to this other issue would solve my problem:
[https://github.com/jsimone/webapp-runner/issues/57](https://github.com/jsimone/webapp-runner/issues/57)

Unfortunately, this results in an exception because the `--expanded-dir-name` param is not understood:
```bash
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --expanded-dir-name
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:723)
        at com.beust.jcommander.JCommander.parse(JCommander.java:275)
        at com.beust.jcommander.JCommander.parse(JCommander.java:258)
        at com.beust.jcommander.JCommander.<init>(JCommander.java:203)
        at webapp.runner.launch.Main.main(Main.java:72)
```

**Comment by jkutner** [comment]
Are you having the problem with 8.5.11.3 or 8.0.39.0? It's unlikely that I will backport it to 7.

**Comment by forgo** [comment]
Thanks for the quick reply. I didn't realize those parameters were only in the 8.* versions. We are a little bit stuck in the dark ages so we have so moving to 8 will be a bit of a leap for us for a few applications. If you know of any workaround to this, I would appreciate any suggestions.

**Comment by jkutner** [comment]
Actually it looks like this should be in version 7.0.57.2. And I don't think there is a version 7.0.75 o_O. Can you double check that?

**Comment by kenhtanaka** [comment]
Some other people in our group started with 7.0.40 and added an AJP connector. They also set the webapp-runner version to 7.0.75 when they set the tomcat_version to 7.0.75.

**Comment by jkutner** [comment]
@kenhtanaka maybe they are building that version themselves? there isn't a 7.075 version of this library that I publish:
http://repo1.maven.org/maven2/com/github/jsimone/webapp-runner/

**Comment by kenhtanaka** [comment]
Yes, they made that version themselves. I see the history in our local git that 1d0b0d2 is the last commit by you (John Simone) and then they added on from there. I assume they forked your code to begin with.

**Comment by jkutner** [comment]
@kenhtanaka ok, then I don't think backporting will help much. If you fix this in your fork, I will accept a PR.
