### ISSUE TITLE
Failover Nodes Configuration Missing

### ISSUE THREAD

**Issue by mathif92** [jsimone/webapp-runner#79]
Hi, I didn't find in the documentation a way to support setting up the failover nodes in case one of the memcached servers crashes.

I wanted to know if there is a way to set that up or if it could be implemented.

Thanks.

**Comment by jkutner** [comment]
Some Memcache vendors support a [comma delimited list of servers in the environment variable](https://github.com/jsimone/webapp-runner/blob/master/memcached/src/main/java/webapp/runner/launch/MemcacheSessionStore.java#L33). I'd be happy to accept PRs for others.

**Comment by jkutner** [comment]
I can update that today and cut a release.

**Comment by jkutner** [comment]
@mathif92 [webapp-runner 8.5.20.1](http://search.maven.org/#artifactdetails%7Ccom.github.jsimone%7Cwebapp-runner%7C8.5.20.1%7C) is released with memcached-session-manager 2.1.1 (it might take a few minutes/hours for maven central to sync up).

I'm going to close this, and we can reopen if you still have issues.
