### ISSUE TITLE
startup is not complete

### ISSUE THREAD

**Issue by asouza** [jsimone/webapp-runner#97]
Hi, when I start the runner, the startup log shows the message => INFO: Starting ProtocolHandler [http-nio-8080] and just stop right there. Any tips?

**Comment by asouza** [comment]
java  -Dspring.profiles.active=homolog -jar webapp-runner-8.5.11.3.jar --port 8080 --expand-war toolbox.war&

**Comment by jkutner** [comment]
Did you browse to localhost:8080? what did you see?

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
